name: Build and upload docker images

on:
  push:
    branches:
      - 'master'

jobs:
  build-master-gcc-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          compiler:
            - gcc
            - clang
          purpose:
            - test
            - deploy
          platform:
            - debian-buster
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        # this only works with github.ref on push not on pull_request. ;)
      - run: echo "Build and push ${{ github.repository }}-${{ github.ref }}-${{ matrix.platform}}-${{matrix.compiler}}-${{matrix.purpose}}"
      - name: Build and push
        uses: docker/build-push-action@v2.5.0
        with:
          push: true
          tags: ${{ github.repository }}-$GITHUB_BASE_REF-${{ matrix.platform}}-${{matrix.compiler}}-${{matrix.purpose}}
          file: .docker/${{matrix.purpose}}/${{matrix.compiler}}/Dockerfile
